# Generated by Django 5.1.5 on 2025-01-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_institution', '0002_branchclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchclient',
            old_name='Branch',
            new_name='branch',
        ),
    ]
