# Generated by Django 5.1.5 on 2025-01-24 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("financial_institution", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="institution_branch",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="financial_institution.branch",
            ),
            preserve_default=False,
        ),
    ]
