# Generated by Django 5.1.5 on 2025-01-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_account_institution_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="account",
            name="overdraft_limit",
            field=models.BigIntegerField(),
        ),
    ]
