# Generated by Django 5.1.5 on 2025-01-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_account_identifier_moneytransfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneytransfer",
            name="status",
            field=models.CharField(
                choices=[("C", "Completed"), ("R", "Reverted")],
                default="C",
                max_length=1,
            ),
        ),
    ]
