# Generated by Django 5.1.5 on 2025-01-25 03:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_moneytransfer_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moneytransfer",
            name="id",
        ),
        migrations.AlterField(
            model_name="moneytransfer",
            name="transaction_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
