# Generated by Django 5.1.5 on 2025-01-24 07:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_account_balance_alter_account_overdraft_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.BigIntegerField()),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_destination', to='account.account')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_origin', to='account.account')),
            ],
        ),
    ]
