# Generated by Django 5.1.5 on 2025-01-24 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaddress',
            name='street_type',
        ),
        migrations.AddField(
            model_name='personaddress',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='person.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.street'),
        ),
        migrations.DeleteModel(
            name='StreetType',
        ),
    ]
