# Use an official Python base image
FROM python:3.10-alpine

# Set the working directory in the container
WORKDIR /backend

# Copy the application code to the container
COPY ./backend /backend

# Install necessary system dependencies
RUN apk add --no-cache build-base libpq libpq-dev

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Creates the static files to run admin and other internal applications
RUN manage.py collectstatic

# Expose the default Django port
EXPOSE 8000

# Set the default command to run the Django app
CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
